### ISSUE TITLE
How would you like to be credited?

### ISSUE THREAD

**Issue by andreaszielke** [AndroidDeveloperLB/MaterialPreferenceLibrary#10]
Hi AndroidDeveloperLB,

I'm using your great library in my pet project and would like to give you the appropriate credit.
How should I reference you - as AndroidDeveloperLB?

Cheers,
Andreas

**Comment by AndroidDeveloperLB** [comment]
What is the app?
What's a "pet project" ?
You can put it either using my real name (Liran Barsisa) or my nickname on
Github (AndroidDeveloperLB), or you could just put the name of the library.
I'm not sure which I prefer.
Just put it in the credits/license/thanks section or something. Put a link
to the library.

Thank you for thanking me. :)

**Comment by andreaszielke** [comment]
Hi Liran,

it's (yet another) Sudoku app (but one that is able to display logical
solution steps, if you're stuck, see
https://play.google.com/store/apps/details?id=de.zielkes.sudokudojo.lite).

I'm just converting it to material design and your lib helped a lot. Once
again thanks for providing it.

I'll add your name, the library name and a link to the libraries section in
the next (materialized) release.

All the best,
Andreas

2015-07-18 16:32 GMT+02:00 AndroidDeveloperLB <notifications@github.com>:

**Comment by AndroidDeveloperLB** [comment]
Nice game. I think you should hide the ads from the screenshots, and also
take the empty space of them.
Maybe, for the lite version, add "ad-based" on the title or description.
I've now tested it on my device, and also on an emulator, and I've noticed
there is extra space. Attached screenshot file.

**Comment by AndroidDeveloperLB** [comment]
I also think the ads do not scale well. Which type of them did you use?

**Comment by andreaszielke** [comment]
Hi Liran,

thanks for the feedback. Could you kindly send me (az.androiddev /AT/
gmail.com) your screenshot again? It did not survive the github roundtrip.

The ads are admob ads. Extra spacing between UI elements and the ads are
required - but I'm in the process of getting rid of the in-game ads; I will
replace them by interstitials in between games.
The ad below the menu will probably stay, though...

All the best
Andreas

2015-07-18 19:23 GMT+02:00 AndroidDeveloperLB <notifications@github.com>:

> I also think the ads do not scale well. Which type of them did you use?
>
>

**Comment by AndroidDeveloperLB** [comment]
Oh, I didn't notice we were talking on github... Please remove my name here, and email me directly. This isn't supposed to be the place for this kind of question :(

**Comment by AndroidDeveloperLB** [comment]
Please email me for those kinds of questions.

**Comment by andreaszielke** [comment]
Sorry about that - sent you a hangouts message.

**Comment by AndroidDeveloperLB** [comment]
No worries.
You've encouraged me to update the library a bit. Added icon support. :)
