### ISSUE TITLE
android.content.res.Resources$NotFoundException: File Theme from drawable resource ID #0x7f07001a

### ISSUE THREAD

**Issue by Tomblarom** [AndroidDeveloperLB/MaterialPreferenceLibrary#12]
Can't use your library.. :(

![hxpbuhf](https://cloud.githubusercontent.com/assets/12703270/9084523/f2de98e0-3b74-11e5-8396-9de599da4c56.png)

**Comment by Tomblarom** [comment]
I fixed it by changing compile 'com.github.AndroidDeveloperLB:MaterialPreferenceLibrary:2' to
compile 'com.github.AndroidDeveloperLB:MaterialPreferenceLibrary:1' !!!

**Comment by AndroidDeveloperLB** [comment]
Fixed. Issue was this line in Preference.java :

    _iconResId=a.getResourceId(a.getIndex(R.styleable.Preference_icon),0);

And the fix is this:

    _iconResId=a.getResourceId(R.styleable.Preference_icon,0);

I have no idea how I didn't notice this issue. Probably some CTRL+Z that caused weird things right before I've published the version or something. Anyway, new version of the library (3) should now fix everything.

**Comment by Tomblarom** [comment]
Yeah it should have fixed it, but I can't update the library via gradle:
![lideowh](https://cloud.githubusercontent.com/assets/12703270/9106158/6c504580-3c1e-11e5-90fc-cc5eeb9b845c.png)

I only changed 2 to 3.

**Comment by AndroidDeveloperLB** [comment]
Will check it soon. For now you can use this:

compile 'com.github.AndroidDeveloperLB:MaterialPreferenceLibrary:5d90c09f8d'

But I'm not sure about it. Maybe it has the sample within.

I've noticed now that there is an issue:
https://jitpack.io/#AndroidDeveloperLB/MaterialPreferenceLibrary
The recent release probably can't be used yet.

**Comment by AndroidDeveloperLB** [comment]
Try again now. They said someone (ahem) tried to get version 3 before it was released, so they've blocked it.

**Comment by Tomblarom** [comment]
Awsome ;) I'm able to use it now!

**Comment by AndroidDeveloperLB** [comment]
Please let me know if you find any more issues. Also, you are welcomed to
try my other repos.

**Comment by Tomblarom** [comment]
Well thank you so much for your service! You're fast and you know how to do it! :+1: :+1: :)

**Comment by AndroidDeveloperLB** [comment]
I hope I will always be able to fix this fast.

**Comment by Tomblarom** [comment]
I really need help with much other things, would you like to help me? k.nikulski [ähht] gmail.com
