### ISSUE TITLE
appcompat library version

### ISSUE THREAD

**Issue by jemshit** [AndroidDeveloperLB/MaterialPreferenceLibrary#13]
can you change appcompat version to latest: 'com.android.support:appcompat-v7:22.2.0'

**Comment by AndroidDeveloperLB** [comment]
ummm... it's already set to be 22.2.1 , which is even newer :

    compile 'com.android.support:appcompat-v7:22.2.1'

However, I will now update the gradle plugin.

**Comment by jemshit** [comment]
cool :+1:
