### ISSUE TITLE
preference.getIcon() referencing a null object

### ISSUE THREAD

**Issue by Tomblarom** [AndroidDeveloperLB/MaterialPreferenceLibrary#14]
I tried to tint the peference icon:

    <com.lb.material_preferences_library.custom_preferences.Preference
        android:summary="@string/scanmode_sum"
        android:key="scanmode"
        app:icon="@drawable/ic_scan"/>

**and getting:**

    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference

**Comment by AndroidDeveloperLB** [comment]
You need to use "getIconCompat" , because "getIcon" is used only on the normal Preference class.

**Comment by AndroidDeveloperLB** [comment]
@Tomblarom Does it work fine now for you?

**Comment by Tomblarom** [comment]
I didn't test it yet. I'll give a reply soon :)

**Comment by AndroidDeveloperLB** [comment]
But you closed the issue...

**Comment by AndroidDeveloperLB** [comment]
If you've checked this issue, please close it.
