### ISSUE TITLE
Icon Padding

### ISSUE THREAD

**Issue by jemshit** [AndroidDeveloperLB/MaterialPreferenceLibrary#16]
Can we change the padding or margin of icon ?

**Comment by AndroidDeveloperLB** [comment]
Pretty sure I've made it like on the standard one of Android, but if you are not happy with it, you can change the layout.
You can do it either by any of those options:
1. edit "mpl__preference.xml" file
2. create your own copy of "mpl__preference.xml" and then edit it. Your copy should automatically replace the one of the library.
3. do it via code, by extending the preference you wish to customize, and then change it for the view with id android.R.id.icon .

This is true for any kind of customization of the preferences layout.

**Comment by jemshit** [comment]
1,2 not working

**Comment by AndroidDeveloperLB** [comment]
What exactly have you tried? Also, have you considered using margins instead?

**Comment by jemshit** [comment]
1) cant edit generated .xml file of library
2) created my own copy and it didnt auto replace .xml

**Comment by AndroidDeveloperLB** [comment]
1. you are not supposed to edit generated xml files. You are supposed to edit the original file. 
2. it must have the exact name, and in the layout folder of your project. I've just tested it now. It works fine. 
Here's what I did to the sample project:
a. added the file, and put there a huge padding for the icon:
...
        <com.lb.material_preferences_library.internal.widget.PreferenceImageView
            android:id="@+id/icon"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:maxHeight="48dp"
            android:maxWidth="48dp"
            android:padding="20dp"
            />

b. edited the "settings_example.xml" and added to one of the preferences the icon:

        <com.lb.material_preferences_library.custom_preferences.ListPreference
            android:defaultValue="dark"
            android:enabled="false"
            android:key="@string/pref_theme"
            android:summary="%s"
            android:title="Theme"
            app:dialogTitle="dialog title"
            app:entries="@array/pref_theme_list_entries"
            app:entryValues="@array/pref_theme_list_values"
            app:icon="@android:drawable/sym_def_app_icon"/>

**Comment by jemshit** [comment]
I am using gradle to use library, so how do i edit the original file? I don't think i can do that. Probably second option didn't also work for that reason, maybe i should download and copy library files into project.

**Comment by AndroidDeveloperLB** [comment]
#1 is obviously impossible if using gradle 
#2 is still possible.
and of course, #3 is always possible.
