### ISSUE TITLE
setEnabled binding

### ISSUE THREAD

**Issue by jemshit** [AndroidDeveloperLB/MaterialPreferenceLibrary#18]
Is there any way to bind one preference to other, like if switchPreference is on, enable below preference, else disable below preference Or should i do it on code?

**Comment by AndroidDeveloperLB** [comment]
Yes, read about it in the docs:
http://developer.android.com/reference/android/preference/Preference.html#attr_android:dependency

**Comment by AndroidDeveloperLB** [comment]
Do note that it's simple, so if you wish to have a very special logic, you will need to handle it yourself via code.

**Comment by jemshit** [comment]
Hi, disabled preference used to look in grey color, but now with latest version of library on Android 6 it looks black, not grey. Is sth changed on Android or library? Updating my old app )

**Comment by AndroidDeveloperLB** [comment]
@jemshit Can't confirm this issue on Android 6 emulator and sample of repo.
If you are sure this is a real issue, please create a new report, and provide a sample project. Current one works fine on my case.

**Comment by jemshit** [comment]
@AndroidDeveloperLB it works, but color is not changed. If Preference B is dependent on SwitchPreference A, does color of Preference B change to grey, when Preference A is disabled, in your test?

**Comment by AndroidDeveloperLB** [comment]
@jemshit Again, can't confirm this issue. The color changes in both themes I have in the sample.
In the sample app, I just added :

android:dependency="checkboxPref" 

to the EditTextPreference I have there, and it works fine, including color change.

See:

![maxthonsnap20170325141708](https://cloud.githubusercontent.com/assets/5357526/24321768/c9461bb6-1165-11e7-91ff-77de5f0d39ef.png)

**Comment by jemshit** [comment]
Ok, problem was this in theme:
```java
<item name="android:textColorPrimary">@color/...</item>
<item name="android:textColorSecondary">@color/...</item>
```

They had to be `drawable` instead of just `color`, to include disabled state color:
```java
<item name="android:textColorPrimary">@drawable/...</item>
<item name="android:textColorSecondary">@drawable/...</item>
```

**Comment by AndroidDeveloperLB** [comment]
Who is "they" ? For me it worked fine...

**Comment by jemshit** [comment]
`@color/` has to be `@drawable/` if you play with `android:textColorPrimary`.

**Comment by AndroidDeveloperLB** [comment]
Please create a new report, with full explanation of what you are talking about, and a sample code. The sample project works fine as I wrote.
