### ISSUE TITLE
Bug: 2 ripple effects for Android 6

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [AndroidDeveloperLB/MaterialPreferenceLibrary#19]
For some reason, I see 2 ripple effects when using the library's sample on Android 6.

I also don't get how to put a nicer effect for the clicking on Android 2.x .

If anyone knows how could this be (and more importantly, how to fix it), please let me know.

**Comment by jemshit** [comment]
@AndroidDeveloperLB  i have not encountered 2 ripple effect on android 6 with sample project

**Comment by AndroidDeveloperLB** [comment]
fixed on version 7
