### ISSUE TITLE
About ToolBar

### ISSUE THREAD

**Issue by baoyachi** [AndroidDeveloperLB/MaterialPreferenceLibrary#20]
about multiple activity develop，should I extract ToolBar in BaseActivity,this can increase toolbar Multiplexing

**Comment by AndroidDeveloperLB** [comment]
I don't understand your question.

**Comment by baoyachi** [comment]
I just say ,how to repeat use Toolbar

**Comment by AndroidDeveloperLB** [comment]
You can put as many toolbars as you wish.
