### ISSUE TITLE
Bug: no animation on checkbox and switch

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [AndroidDeveloperLB/MaterialPreferenceLibrary#22]
for the preferences that natively have an animation when being toggled, the library doesn't show their animation.

**Comment by zacharee** [comment]
Are there any plans to "fix" this? I can live without it, but the animations would be nice to have.

**Comment by AndroidDeveloperLB** [comment]
@zacharee I was told to use what the support library has to offer:
https://issuetracker.google.com/issues/37103112

But it still doesn't work.
So I created a new report about this here:
https://issuetracker.google.com/issues/63456897

Please star it and optionally comment there.
