### ISSUE TITLE
EditText Message

### ISSUE THREAD

**Issue by lucari93** [AndroidDeveloperLB/MaterialPreferenceLibrary#24]
I'm using EditTextPreference in this way:
```
<com.lb.material_preferences_library.custom_preferences.EditTextPreference
            android:defaultValue="@string/a"
            android:hint="@string/a"
            android:inputType="number"
            android:key="@string/b"
            android:title="@string/c"
            app:dialogMessage="@string/d" />
```
but the description isn't shown. Where am I wrong?
Thank You

**Comment by AndroidDeveloperLB** [comment]
I don't see you've set the description. Only similar thing you used is the dialog message.
If you want a description below the title of the EditTextPreference , you need to use android:summary . 
It's not something new. It was always there:

https://developer.android.com/reference/android/preference/Preference.html#attr_android:summary

**Comment by lucari93** [comment]
Sorry, I used a wrong term. I don't see the "dialogMessage" that I've set.

**Comment by AndroidDeveloperLB** [comment]
You wrote it in the end :

"app:dialogMessage="@string/d"" 

But I see it doesn't work for some reason. will need to investigate and fix this.

**Comment by AndroidDeveloperLB** [comment]
OK, fixed. Try newest version now.

**Comment by lucari93** [comment]
Thank you very much!
