### ISSUE TITLE
Change toolbar title color

### ISSUE THREAD

**Issue by ClaudeHangui** [AndroidDeveloperLB/MaterialPreferenceLibrary#25]
Looks like the toolbar title takes the color accent as default...Same goes for the home button..
My accent color is somewhat dark-grey, ......but all over my app I use a white home button and the toolbar title is white..I'd like to apply it to my settings activity....
Is there a workaround for this ???

**Comment by AndroidDeveloperLB** [comment]
Sure. You can do what you wish with the Toolbar, just as I did.
Use "getToolbar()" and change the color and whatever you wish to it.

Alternatively, you can override the resource of "mpl__preference_activity.xml" layout to fit your needs.

**Comment by ClaudeHangui** [comment]
It works for the title, but what about the home button ?

**Comment by ClaudeHangui** [comment]
OK so for the home button this is what I did (basically...) and everything's as I expected: 
 Toolbar mToolbar = getToolbar();
 mToolbar.setTitleTextColor(ContextCompat.getColor(this, R.color.white)       
 setSupportActionBar(mToolbar)
 Drawable upArrow = ContextCompat.getDrawable(this, R.drawable.ic_arrow_back_white_24dp);        
 getSupportActionBar().setHomeAsUpIndicator(upArrow);

**Comment by AndroidDeveloperLB** [comment]
Yes you can customize it as normal...
