### ISSUE TITLE
Need help  unrelated to this project.

### ISSUE THREAD

**Issue by himanshu-infield** [AndroidDeveloperLB/MaterialPreferenceLibrary#29]
Hi Sir

I need your help regarding background service in android  how can  i reach you.I would be really really thankful if you just take out couple of minutes.

**Comment by AndroidDeveloperLB** [comment]
Write in StackOverflow website, and let me know about it:
https://stackoverflow.com/

**Comment by himanshu-infield** [comment]
Hi Sir

PFB the link for question and suggest something

https://stackoverflow.com/questions/51610409/enable-the-background-restriction-and-allow-app-to-run-in-background-for-long-ru


Best Regards
Himanshu

**Comment by AndroidDeveloperLB** [comment]
ok answered.
