### ISSUE TITLE
custom layout

### ISSUE THREAD

**Issue by jemshit** [AndroidDeveloperLB/MaterialPreferenceLibrary#7]
I'm trying to use "setContentView" in acivity class and it has my own toolbar design too. Below toolbar i have ScrollView and ListView with id "@android:id/list". Does this library replace list of that id? Since when i use custom layout for activity, it does not scroll.

Default toolbar is ok but i can not change title color and typeface

**Comment by jemshit** [comment]
I had put listView inside ScrollView so why it does not scroll, i fixed that and i can use custom layout now)

**Comment by AndroidDeveloperLB** [comment]
You should check the code I've made, to make it fit your needs. Sorry.
BTW, about ScrollView, it's recommended not to put it in a listView or vice
versa. Watch the video "the world of listView" . They talk about it. It's
an old video, but it's still relevant .
