### ISSUE TITLE
Title background

### ISSUE THREAD

**Issue by jemshit** [AndroidDeveloperLB/MaterialPreferenceLibrary#8]
I see title's background color as gray on API 10 which is different from API 21. Is it normal, on library page both images had same looking title?

![erro](https://cloud.githubusercontent.com/assets/1948828/8638155/2ac79b30-28ba-11e5-996c-494a614e3125.jpg)

**Comment by AndroidDeveloperLB** [comment]
When tested on the emulator of GB, it worked exactly as shown on the repo's
page.
I've tested it again, and I still see my own customized header.
