### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by jemshit** [AndroidDeveloperLB/MaterialPreferenceLibrary#9]
"android:icon" does not work on material preference list items, but works on default preference items. It would be good if we can use  "android:icon" tag

**Comment by AndroidDeveloperLB** [comment]
I know. I've already written about this, currently on #4 of the notes.

**Comment by AndroidDeveloperLB** [comment]
ok, I've added icon support. Example of usage (for any kind of preference class I've made) :

    <com.lb.material_preferences_library.custom_preferences.Preference
      android:summary="just some summary text"
      android:title="A simple Preference"
      app:icon="@android:drawable/sym_def_app_icon"/>
